# RTX 4060 Laptop (Ada) - Hybrid mit 780M
options nvidia NVreg_DynamicPowerManagement=0x02 NVreg_PreserveVideoMemoryAllocations=1
# fbdev=0: die 4060 hat kein Display, soll also keinen Framebuffer greifen
options nvidia_drm modeset=1 fbdev=0
